platform :ios, "13.0"
use_frameworks!

target 'Kline_Example' do
  pod 'Kline', :path => '../'
  
  pod 'SnapKit', '5.0.1'
  pod 'Starscream'
  pod 'ObjectMapper'
#  pod 'Reveal-SDK'
  pod 'GzipSwift'
  pod 'RxSwift'
  pod 'RxCocoa'
end
