platform :ios, "12.0"
use_frameworks!

target 'Kline_Example' do
  pod 'Kline', :path => '../'
  
  pod 'SnapKit'
  pod 'Starscream'
  pod 'ObjectMapper'
#  pod 'Reveal-SDK'
  pod 'GzipSwift'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Localize-Swift'
end
